apiVersion: v1
kind: Secret
metadata:
    name: velero-secret
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:n9vSCWPwxgGCRc9k0q8JHA3o3FMktVAFlxqWczdoQ0z2W+43PyEx4rfKaPMZl9nTIi9soXMONArNC2HzCHbNKbxFUyf2nQg0aOv1n9GhUbu/JNM1OJfwbMaeALL+br6qrBUREnEXqHg/i7dKavpJZjBT,iv:b26LXLu6U09SB/Wpp5rzI1VikA2gWyNH7vO8H41Cbkw=,tag:+/snec1C8KddSLbPpAkQAg==,type:str]
    repository-password: ENC[AES256_GCM,data:sWclIRGtPKTRXvFukl/CArE=,iv:X6GpPU2l/zR9Kqf7N5N0xe0uT1EJJXMFbTxYHMjK5SE=,tag:6kUNAM9Q8Mu3QPTQ9GwCgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUzZseGp1SGVVcnk3WGht
            Y1NkQVN3RHRLbC9qSHNhU1loTzh6M2FYSkZJCnRrUWxmcElqeUpNd2tZMDJualpS
            REZMdmFwN2x0Z2lTRERPdng4bTZ2LzQKLS0tIDNSMHpyMGQ3OGw4cklmTURBSEFC
            L0ZVTXZHeDJTVnlrWFhBbHdVU0hkVjAKmoDRPnuLSiPa2xlZyEew7xatVnN1/VEA
            KKCEvHXespB0uEEEObUPPMv2/iJ31lZgt7QA6le7BUE8TFFCxtoVJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-19T06:11:18Z"
    mac: ENC[AES256_GCM,data:jJcI1RRMb7NJ5pHCayM4ozeMQl3VfV1qsxtVc8OQzBspy3Eqw6H9b0UMvyW1JvJKKKx9zNxIKQE3dFSiY7MFmGjJGbjL18qyz4A1QzNOVd+35NB2WP+PgI0s39OzXM70582Th5X+gppfT19dgnXBxvWyE8xYnZCgz0fuvh2S6jM=,iv:mHcVSXgBrXAxGlgkwxMetuHScGsi7n4jwjXdwAWWDT8=,tag:PrD3ssl8sMwhy2DD6W0oYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
