ansible_become_pass: ENC[AES256_GCM,data:/H00TuG9zg==,iv:QOIF+OudDSL/4I0YtfJbalBU2NOZ4c5HGXxmbOQN/6g=,tag:thol9Pogu9W/so36MwGeqQ==,type:str]
ansible_user: ENC[AES256_GCM,data:IV20OQ==,iv:OCpjHEnbM2WraiXcPU7FaksDG+8vrtbtdm5jiQYGpxk=,tag:rnKu5jowWAf5qpnppeJLxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUDN5NlNwQlgwWU81YTFh
            cW51bG01VlNvc3J1SGw1NzNhbWg4amVwWWhRCmIwZmZiY3JYZWxKdzhaMUtVdEVj
            MXJEVy9oS1dEakxyV2tLNUFIYjdIZG8KLS0tIG5xbXVpTFh0WXZHbWhIS3A3Q21L
            SWdzKzYrTWNhMm9uWGZkS21PZ09laUEKdjL+6FV2ZtvjaH1Hc9lnsk8+hw+HmM/p
            /wTQkSwda2oNiPMTZ6vhVy3v3FlZkNUqqaJdcQURxH3R0J6x22gDxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T12:44:31Z"
    mac: ENC[AES256_GCM,data:tZp80O91xOueAY9N3Cch/Ayof4V0rSqJn1ZgxHiHfiK0P4laxjaWFuny+0c0LNr6J6NnAFE/NOLcf/A9hh12xJpXiTR91x8F/z35W7wUADlO0WLTwpZ/3ksPl1Trwagg2PZOHeKDSie26DbUABEiDPR+l3jKSyduCpmpG9wd9A8=,iv:usNqKMfridXBdijUhB8uVTgYCT/lIWW8w4EtBfGHNRA=,tag:5V6at1Fmf31rEd4W0FtLMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
