ansible_become_pass: ENC[AES256_GCM,data:gJa5TWL6uA==,iv:AqWEfmKg2mqPIWp4HfgAIHNdQePcn3noPYcg+dy6ecM=,tag:BtbToX9SlPMofGXjGxROHg==,type:str]
ansible_user: ENC[AES256_GCM,data:n9clYQ==,iv:w2tc1CR5X2FkXogTCZpRvAZtUNW/qDiUYW1Ciz9/ecg=,tag:cuj0a8WYf6oCAZwMfcgQrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSWwxd2tTWnFzMnVQRXRm
            aHJOaVg2bDhsNHBTRHVZTnh0cDZVWVMwZmdzCkpPK2tjeW5ycklQajcvYnhyNmpE
            TmNZT2RVclBhR2MrT0FySDVtd3VKajgKLS0tIE1yZHgzTnhKZmpUcGRkYVNiRXFV
            OU5Da1NZS3Zjb1dqazlFcy9GdEJqUUUKpO2ZMTfhzgAZPmX/U42/xTEfKkasi8dS
            ob/hIUa4o2OLgA3WHFTJUPONS/hFpQpUpao1u/7shI5X8gLWweK76g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-12T15:58:19Z"
    mac: ENC[AES256_GCM,data:l5+//rq69sjxZx1W/nN6vk3Wjlvrpo4T8HQNNe4uqPXbIjcXUK8AsCpeyKrTvfU91V0uJtG88LveWyQQ3GwyEnsp6vua9vnlplBxMl8XP/8YxklZ6C5tBefT+Jt+EEZVODfbgGSHwFRZX7z/POsh+KM4WBjRK+nKBVZGjIwkbUA=,iv:kC+/elD8XNkBp/cmqD5ex4S0BScgJ5hXuTeQHINwDZA=,tag:iCiemFVp8zCp6fCzXaO19g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
