ansible_become_pass: ENC[AES256_GCM,data:EYblxMCduA==,iv:mays0QcmIfp+rmkR0nlsThikYWpyuv7fuqLD38psv/0=,tag:cwJJzoN0gRsBNaYPq2v4/Q==,type:str]
ansible_user: ENC[AES256_GCM,data:bm9APmA=,iv:eMHNQX1Qt19SQrEyqDh6qXW05ar2odOnVgBzM3h8XLg=,tag:pdqPHGH0DFBfSTAy0d3tZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeUVnY0JPSm1veVluLzZD
            YXhib3Q5TWdhYUJ5OG40STVHQmNjakt2VUVjCmhCbDdRZlYwcEJFY2cxVFJkcjBt
            Y21FbW9DdG51ZCthVEpwNVpxcE95RjgKLS0tIElLTFk2VUtIQm9ka2VUVVdPZkFn
            dS9IeFJnWUdsSTVpVHU5aVVWZDB6cFkKkS5HMJvzWFtoZd3W2DWeDR7aS7oRrL1e
            nooxZO++D1UwrfKksRmxPKTBX8rEOnKxGQiUMOKg6LKZW5YfX9eHOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T09:48:59Z"
    mac: ENC[AES256_GCM,data:fHrQaXEhPQ6x3IgtaVRK3odVYpSf55s7qL7vQeZGP3znDuOtAHnuzYkO5sM2vyxm97mmk+/Dyy2gAdNoxzUY6jWC+t113sXPC5+9+uAfbgjKz4Qr/WzIjqCff6gx20XOZeOi/i4PYhezQPYFjIblNnVrHmc/ikXGVgTa7vFxoPg=,iv:9X5XnP0M+aR+LLmLvc5e5kWE7eMKujx+OC2PydQyfUk=,tag:ziXhLCnp7Hnxj5d8I2/UeQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
