ansible_become_pass: ENC[AES256_GCM,data:kT79+/hApQ==,iv:qzpHNtJEc1l8Bp1Gzjp9bxaMq8vIj9rHhUVWragH7S0=,tag:WzNg/s/SfBrzTVDdwiyItA==,type:str]
ansible_user: ENC[AES256_GCM,data:cpV9Mbk=,iv:UEbECQ5Wn7ioXPyE0aufbvnM9vMACYoq5Idcn6OcmWQ=,tag:bJSlrr2IE7MiwzWeckzMCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVkYzLzVvR3RFaVRuRy82
            OElLZ0tmdDdnTE9iV3JlcUJmbVdhbTBjYXdNCmxmMlNhRzF6c3lETnkyZUZ1dDhQ
            bkY2NVc3VUFkZy9rNkJUckVQck1ib0EKLS0tIDRIdER6QXkyYWUrOEtGeHJ5bDhw
            ZkVPM2FDckNoclpNdFFaNkYvT1Z1aFkKQELIxbW2oVxmVw9kecjeYyV51gsS3zuP
            WGty8xM3jD5t9dY81duSp6PrJCCNMDxwnWFnR79+uJz5lG0csuJ6Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T12:44:32Z"
    mac: ENC[AES256_GCM,data:7I586+YeRkDx2vwF1mcUffU8ZU5+JKG+ooHRTMyAEjKxMHxGfm1+p8LuNRwzJdTESRGY0WHCA7Qec53nsSr7yk9FMUFGf4GdGPeWJjxmpwWZhOP9AE6bFz+10eWqii3fYXwqPNztKaGRGOxwErf2kJyg78hLkjOOYs+vHxVICWg=,iv:OlDB8e225w4TNhE5MhqZA0vuzRoGw3NU9/+rPjgxLM0=,tag:YJi0qEiK5yCmQghtmqnIaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
