ansible_become_pass: ENC[AES256_GCM,data:/AJDd+W+GQ==,iv:cU6cpQrAXAytrf3yIEa8ytX1PPivqQl6vpnudXRUoKI=,tag:1vhvFK3bCFukUkeuJDy0Pg==,type:str]
ansible_user: ENC[AES256_GCM,data:pDCjnyI=,iv:liZbWE70JiJfM4oNk8dnZu1wNTi7m8Y9vpF4fdvNQkU=,tag:fA7dQFg+AE1I912USzq6tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK2hkNG1BUE9tZkpBaHV6
            Qnd1dnNvSUd3Rms1d0dQYzNmdlp6eUVwTlc0ClppV0l0cGdJcUNEODhwU3dlVTZy
            WDdxVWdkUUdZVTJySUU0YWQwSlFVbWsKLS0tIGZHdDZUWmVGRnlzb2FEMldxei9r
            Y0dPTENwMnJMcUlyKzJUU2s4YVVkTUkKUGrgHIV6y+JbiLF8HY6UqYA5ml+aP7OT
            9ZHvNdkQfAlrhXgMDS+jLScWzr+dj1JP3/gMq9EhJgR1MztJzln+eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T17:12:22Z"
    mac: ENC[AES256_GCM,data:Y5/SshaeuEHldis6DnByzQQCpzZh+XTLx/CFe4CyhnjBz20t8JBlG2a6lCJSyWKg8qkn0PTknDs3IWW/TP6LvBvTOB6dRH1KiBA93o5oAFx3WEFtvcHcbfkmwGUlsWL6b1+1898i3xY1FwnmO5uPxpkIwEowBBDsQFNTCtXoEs0=,iv:Pg21KAn8K378o1wIn2m3lpWyDc8kaWvmRXMEuARiw2I=,tag:/6LXpbSX/0s8LH8DHFC+HQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
