ansible_become_pass: ENC[AES256_GCM,data:W/qKMhJVjQ==,iv:hhOZrxwXOHe8iVgjNIU3Zy5d2ojBkgs0ut2IgYIOE6A=,tag:qMH6Tnwp1eORaT7mbvW+XQ==,type:str]
ansible_user: ENC[AES256_GCM,data:eC7Q2mA=,iv:0fhvIik8KbbXGhkxbuADH95+ueFwjXuahtXZREHCcTQ=,tag:ET6kGm9CNH9EjzQt3+2sVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMmhHZ3JVR0NnWHpRYlZn
            eGtPWTZsWEdxNzlwMmNzdzN2ZkZwaW1haFc4CnFCMW9GK2NCK0sxNzFBSXJYYVFW
            RUt2STI4WWJhV3hlVmhaZDJKV2poVHcKLS0tIGFseTNVRTJTMUczNVJRdlFHeXM0
            UWovSHdHQ0hkWEJKQjVZMUgvMnIvL2sKNAfF3bBP+uHDv3G7Rpvq+oYSLJwCiq9i
            k0Pqdk0quohDDPToQQIxmF0HL9GOjGDXdgYTbJkrA49YEqIYX9NdJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T09:49:00Z"
    mac: ENC[AES256_GCM,data:X8Y80SMhVTXImuGqQJnYPAuMA+Z90yDrmHWTPy62kw+E6qcqu9vNWYrsnX57baFFn4AQJ/WK5ycVZpLY5hgVIuk1UVW86WHuNgFDLOXqMJV/HJmLqYRiwKX+6xJ2hze8YCT/8OTu5kZlUS87ZPeC2MTvg+MljQYglQOkahDD92Y=,iv:nE2TPobyuVeK/T18AyCPeH5C75d4+CLJs2XHRwdfuVI=,tag:y/xyisTrLRQ5oRXAg+lEKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
