ansible_become_pass: ENC[AES256_GCM,data:qCNsvVkcrg==,iv:OnwdkcMDzLlzYtGR/uIGsc1DUAw2dXafNja3Mbb7BN8=,tag:YRlqXS7gSjueAzpjw1BnhA==,type:str]
ansible_user: ENC[AES256_GCM,data:i15AlMc=,iv:GKfW1+GIUsSQ8/jvVuOawr22E4HIDjJXpEEe3nkbHz4=,tag:a/BHL9HmCvxtRHCSJ1CbhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZHpma3Fjc2pnUXBSQ254
            aHVXOGRDSUJvNWplVWNPTk5TWVZEb0E1OEhrCnpqNlZuTUNMWFZaQ2pMTllRZVhU
            S2NCNk13bEtlZ05kbGtwQ1RpZWIyTE0KLS0tIHlibEF3OG9rNTRlbk9TTFpwQWRQ
            TGcwbE1rTFE2S2MxaDExdFBRYVR0bkEKxHK1kPZueSReHnT2+yI9ngBgyBXzL5pU
            g5VC5YidJyUndArWeuacZlDhmrOfiSSc1PaXzKyySx4Xgba9/PtxkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T08:12:42Z"
    mac: ENC[AES256_GCM,data:h/ZKcL+UNIr/FnRUah8SPrbpn7xJraqn00XGVZajVq4+OGtxL0sm9/yy5bFC60weaxxqXFygwhwR4qtUX4bi9tR8goiijoDGQvKr9lCQnaEDdayfGpSqmj9uv0nYJ+fzEoEaDQsQrqu+5vyLx1TeLOsbJ3ERGjXkRTFI5Us0lPE=,iv:4eAGFj46jBnfBamLqivvnOccK/ZsKWvIs1mbWxE8G+k=,tag:TiPzf1KJb8vA2vhYDHOwDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
