---
kubernetes:
  children:
    master:
      hosts:
        vm-1:
          ansible_host: 192.168.1.98
    worker:
      hosts:
        vm-2:
          ansible_host: 192.168.1.99
        truenas2012:
          ansible_host: 192.168.1.101
