---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  sourcePVC: registry-datastore
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: registry-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: local-path
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    #https://volsync.readthedocs.io/en/stable/design/restic.html
    retain:
      hourly: 24
      daily: 30
      weekly: 52
      monthly: 12
      yearly: 10
