apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:eLs=,iv:3cov7QrLntTnkx2WzNe8FydNC6K85OmIgZcx1jtTmq4=,tag:3O+cAffuS+/m4loHOSWBlw==,type:str]
    username: ENC[AES256_GCM,data:RM1MrII=,iv:4FThcHdsi4XYqkIb8vrUw68N6Ff2N3un1qRGqMhD4wM=,tag:9qaPfuxbztE0rDDSHAMNdA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWkhyYXFWR3ZRVCtyNjRB
            N3E0RDYrZWpUNGh1ZTMrTWpqR1loS2p1UEY0CkkvVisxcGg0Vkljb2RjOHkzYkw5
            aXJOUk81UDQ0SlluRmorSFF0dVN6L2MKLS0tIGk2czl5ODd1K1g3WmNKS2tCeVlT
            QmxDdDVmdFcxTkxvUnVMKzk2QkZydlUKv1Ac/bCYFsYwtW1HZfpPF3L3bWGHcD3g
            w868BaMbXYgBjSAa1Fst6MGNDkgBLJTfAg491eqYTeGyYRFlEk8LKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T17:13:26Z"
    mac: ENC[AES256_GCM,data:bj3hvuWoJ682nJJmuKHvSlIDh7+nB2eFDlPlz5V5zYkyMIFkwLEKT3j4zfSScmeiLIy6tx4Xu9d+teRpN3qMz2oEOC6drIxzDPHyaOS69OwF+vWkWxOAXgzB0rcybiY/WCREm2YqdYh849yRbPO6Ec5+qzEcNlEBnrXB94zQUA8=,iv:t7YDDXm78VKeteH9Hk6D1msxhIQ3H+c+DpPWNWzj7P4=,tag:P1vO9pT+8yMFeDf2M5NCyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
