apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FzLf0GcOIbCLqud/Ca+9CkhzKtOkY4u2Wb4=,iv:KOVzTOsem5ZQhE6L/OhtMW0AdtMeJsrAarxaP8Ioci4=,tag:QCVRkHk7gT0uskYM44xU9A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:jkjQ+yVyiQAwqqPunpM6j2J5JBlsBqFy/SD7VbYU7iij+XTz,iv:bQyoPLaaqtzXwfwGWBiEB6VQSx+sO/S7LClX18T312o=,tag:5ST2oxy591G4XHqn1BoY4A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:2PyBsp4RuLVyXw==,iv:LXF1MCX1iSvKIqKzwfkzzaMdRmVMfokd8XYG6glNC78=,tag:vSGCuxddudjiQLo5XwOj4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa0dnbE1zV3F3cE5jNmx4
            VUY4emp6aFhLWmgrWTd1OXFqVEU3R3FxSWlNClZCZDVMS2RGdjljanJKcHlRMENx
            WU5TdUVRWVp3OXFNMDVjTjJuODN3aE0KLS0tIDVybmovTWtqRUh2UnRINFFOd21M
            Wk82RGpNUzRaREZpZTlvLy8yMmFscU0KcVuzKqz6UE6JjTcyZe4DjlFeBmLTA3pR
            LiLyW5VEx13AcsFA+W6DqE/J/SWRvcDpYCiSy4gaPt8c4BbhWDO+/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T05:11:53Z"
    mac: ENC[AES256_GCM,data:ZGNqLI4kzUHCYVTaG2J9M9in4QTlnt5t4VnDv7OtRolCbskddmlhwAUt+TdMUT821e8c+ucvQRkLmzpyOaPMsWq9WonUYR6P7j0yHpeRU3Kdoix4ygiRiOrquEoYbZw9GB+eQ5E1vJjB6LenRUzCMb7DOSclPnou3Vk/4/+7ieM=,iv:GFrZZoHI0InjfZFNKUr4BubVzv5UZb5fo570VAD+Ugg=,tag:fHWFgjcM2lRejhBhSt8fZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
