apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Pvf9GQSOVjJBU+G+nPr5sA==,iv:ymC7HvPUx6vAZqjnWRVwNRT/nJjvFJRFwKYPKCysc2k=,tag:dgvMgQ1v2G4VujzzMF/dqQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wvgNGeCrplcv7sJtKp2fO3Q+X/Rid3HWTP7got6VR9KEtLB+uSNWcA==,iv:/XCdisTwwOkXtk+DBZAx36MheANliDC6odK4y+csmkE=,tag:X7S/eghH1fGVoySnilgQhQ==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:vCbhwGvCuZleOlpIVsxbEPRcxEdMAmQpkb5LopHRdKAy4jxv9eabuw==,iv:lY2jZ2FQhwiDxLzGqrAMroexNI83OWCp7G5OLlsZQCE=,tag:cgHs/uqi8Gt4W/8QrtYaYA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:wRyEJiM42dlpjYUZR5C5vtk=,iv:VmVd6lEWzIyIccc42hR4j3MInN16CpOfwuPAPk56qrU=,tag:AwZQJXc4LAqrveWbeAI4dw==,type:str]
    S3_RESTIC_URL: ENC[AES256_GCM,data:25z+F+Zt/T0XY9327Oq4c7nGN1ku2cpYZAUIntyusA==,iv:O2E2R7pmpE5o10CB1bpWenC+UBKUzbxQ1KrtWjELx0A=,tag:ZAmckI2KhDZ/BpBa9NKg7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1enpFSEFBVkFFcDNabEZW
            L0tnbW1HcGRkaTJHNGZpZHlhVmhoekFpYlN3Ck4xeThjK2lBKy9tekNoeXErV213
            c0JYN2NOSnhRd2RrYTFPR2lkVlc3Y00KLS0tIGMyc0h4WWFEUktXWDVlMDVJRlp5
            U2hBbHFFUS85emllY0JBK3MxRURxaHcKip1g4JxezwEoLXsfphOY+MZ9yUBtfo5S
            M7jcVDIFVNf3TbybxmQMqOyvoIrEaxtpcPkqI0me+3VVD7nr6XA/Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-21T10:53:01Z"
    mac: ENC[AES256_GCM,data:n/jw98/kF93XinFt2Eb8552V6g70MfbEOcNYr2suu/XGtDUhQeRyawcZQcpXDKCXiQuLYMtfrhgVt+JCGEOeLguTjiUnqLmYsniIE1g1rn2aCt9FrhZXdTSgKB1yCMQ969p9qF1DVKR1/8WXO38b4/4fnPpdsFkLKvRiClluTeI=,iv:Pn8y3XlsSkpR6/BNgny7LS3eJCkTWqw8InVhu5oGIcM=,tag:DowyYOZzqL5kQhK6SQ9qUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
