apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:puHE8MQOvneBvr9/,iv:S4WHPw1OxZoHojpyAjVzfjgYmQ611W5wX939FQfv0GI=,tag:kaoWgsB57cYdpbG6XmcHEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTnBkTzAxZVhBYytxaFdD
            TUtXZEREcXBYWTkvTGJnRmVPRHhScGY2T3p3ClhGKzVSSEF1V1lJMm50UVVpTmZW
            aVR3SldFVWtEUjAyamdJY1liN3p3dkkKLS0tIHFmY2NYaWppZlBndWlHQ3J0dTFs
            d0M3WFBBZU1XcERya2tNSlV6c2sxdlEK2MaR8gCf8Wcys2K+v4Inw9lDKGdzPdew
            laViP/dBeHozv0ICUgTFMfW7Z8MF2N+VJm5g29Z7LPkzrjYQPrg/kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T17:13:17Z"
    mac: ENC[AES256_GCM,data:sAzCdp+leCRVnfkEGFpK5JYnDb42cfgA/Y+R2D0xRUGyPCRemMNQi6dMxVELYnHYO/7UMAtBHrpiBTeWGNn0FKG/rwIHSF3axJpFYO8uvdtP8E0mX+xHKCBpQ0PkaQgw2kkFdsiAISd34GCn/NvfES4OfidXkr+YcADwmrGN7DQ=,iv:wtrcwu7r69FK7PRJabpsW6BkC6f4vfFUHpXP4hyox0s=,tag:EmPzjxZLB4xLr6pqTuupPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
