apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:paVVO7RpiTADfwNbYXqW9g==,iv:jB60+jEVjGN7bp7bltkH3LmWZwy8jKIaG6jEv31hW3s=,tag:0T7fV2jCVqN6/YIih6q+UQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qeaVY9FFp3a/DSrM2isU33XURhIefHEjcIHTMKRY1JY5iweaNJ10fg==,iv:s1R7Q0pLGoVRX58XrPnyDNdbDC+eQSrnc9AADvQvOs8=,tag:NleXCWUdqVjoJynpfHb97g==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:W2+58Y2Z5f61giOjknJyY/3dgSzuWEHvFOWx/V8HANrR7YtV+y9aF82Guq6GcO6JZknQnpTnrqf3h/I8L01ULuLqUc/NDpn3Aydom0AHlc5XgivwRcCcxB4=,iv:4ab3KrExVq6XTuWRZHXrZbVRwCqp4Uqw9Y/ryx9Ye54=,tag:YxW1nwzfsBeYzrc8WrOACg==,type:str]
    INFLUXDB_SECRET: ENC[AES256_GCM,data:7EFUCJAoxT17IdFdfTwtoiX+BzMRoqw02NAy1GbJaBp7EpdJRSEzBHlsxd9IzSJu4f2qpuANHFjncZ0r2cPeL3N/PLAKyCcicmczXvUu1S/SLqiLVxZdhw==,iv:EzLwUhHfM2hfQurvIQaIiH5EfbV2XncK9Iet2LLbFcg=,tag:u+cMsXJKWg2IQnE7MqZ5Sg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ICcslCzqCyF/dX3/vyiFLRs=,iv:QsirknZtM4L+2/peDK/1kafhv8vOYNi8VsMj7c+ni4Y=,tag:2ZCeQyC6gq3zS2hQ6xyXnA==,type:str]
    S3_RESTIC_URL: ENC[AES256_GCM,data:6lg4lp3xvFDkWkv4Oc9MMnHDIV086nq5OuG8551bBmylPXtMtPajyltO0ZglbZruqwqBWJg=,iv:ea3hHNa9H9xqqG7ptE0Jw0c7AE7iEhG3jp7gziFPx6o=,tag:Z8mnsYJsraelUFbbOulR5A==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:riV3WZSlGw==,iv:FQk7UxMumlcNYMn11J+IxebNTqvoTiHSTm3d6kDZtp8=,tag:e4n4RETemkyT8ng6YKrUjQ==,type:str]
    SECRET_S3_URL: ENC[AES256_GCM,data:y2CVS8tBZpAi1wll5A8lZY+xbUMNb9qs3R8D,iv:XHl2lA0LeThaR+Zvqx57/G8bgLyckb6UHQYUk8DS1v0=,tag:4MGwQo+mjlUXdBhA4GRsfQ==,type:str]
    SECRET_USERNAME: ENC[AES256_GCM,data:E7G7h98=,iv:ZqoWb3Pl0yfODnF2ThJFmx+2Z1gP3B89xri2mQH/65U=,tag:xhomB81U/CEgWU/LWpZJWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MGxyazFRbWZBVEh4ZG5n
            eVcvcHpUQk5zdjgzSUNJZUpMYVZaRXRBRTFnClNES1pIZVJRMEVtc0wwY20yS3J4
            ZUhrZXk4OWp1NVZBVitqVitubnNPV28KLS0tICtPQXIwZUdiOTlscVM2OEdpT3Jj
            N2N0OHZCbmd4K2o1bklISU9lb2FmTXMKl2r8RGUhy9Le/M+99x4+PHT8nMLN0hF8
            nfExetz/zQDDb+Y8iBkjxSQA8cePw7omA/wPyylaV9hHG2OBCGA9hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T08:04:46Z"
    mac: ENC[AES256_GCM,data:/JZMK2otFkPGhztC3cHKqunAanvfDFBWEc8Pn/jzFstseWHcwnQJIzG2Xxant9izoldwAD+Pe5ONNHCH8sg9WNqItJ6g+ZOs4aYxElhwawQlt6lgio9LFjnsyxj3a4d8590xLYCUE6D7YdPbI+1M720AFs9647adfUycTrYHYI4=,iv:ZvDsrUSWwMmsI4ueR421xGjurxjt7qBVplKM//r3S+k=,tag:1X9lRp9M/GNqUhCAPF+tlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
