apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:195ldJir1TLZias+Fo+bRKErqTEeN7/F9qk=,iv:P8/nJZ1QfkjiPmF05VFVNwkUBhJDbKSKMRTcQcvq2co=,tag:R48WGFS5ZV9YiApSNAtRgg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:my4SonD95ZTALWhhpEPurF5fi4BWvYsu8muzLJsJfAdX7yd+,iv:xwAyVDoO73/WBGE3jaCCgEmUsKbWPQFGLRgtlcNEiDM=,tag:UGnDDJy61K2GdjlwEHHXaw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:+ewnxcJvpS5/TA==,iv:aHy3Mp1xqUwfcMqzYZ5A3HRFLquPZkT0P5OiP1KE/XA=,tag:S4S97fQ1yhv2moPpMiMMCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS0E5bmlNcjJpb1E4TEJj
            Y2k2b3p0TWJJL0lVSnp6M1dJcjFWWlFiVjB3CnpOdlB6dDV5R3RVZ3dISmR2N3o0
            REN6U3lLdy94Y1NOQTk5Z2Jnalg3cncKLS0tIDYzWTFMalYyMVlYOHV4TTFYSTUw
            N3ZzL2ZWZEVxYVFNclFSWm9DSmNRdUkKGGli01Fr0F54TaDpTd6kDioGluKSC/8f
            7uibWOMzDjZCCTIIquZW3fAcdPKPPftavmagUFUNLzckqpnYKmfWIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T09:45:38Z"
    mac: ENC[AES256_GCM,data:OSDL72Dhr55k6MTpV0GaGOaIN+rzgQdd0R8TTJ61RKvPsE/O3LBDwDJ2QlukeHQzFRVFtoPlvMdA43bfescLNwsGkAX40T1W+9N36Nzlu7wS5y0hlTf/BuRnjkUeCLCCggCFuP+gUAs0Y7eoVATnGcXtf7gy64s+dorj4T8rL0Q=,iv:Uhr6/wh6ePUuTQ+Sg673Lw9u05jBjJfRS52bt3g/w9E=,tag:27IrawlGxnz8qqCZpcMlew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
