apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secret-test
  namespace: default
spec:
  target:
    name: cloudflared-secret-test
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .account_tag }}",
            "TunnelSecret": "{{ .tunnel_secret }}",
            "TunnelID": "{{ .tunnel_id }}"
          }
        TUNNEL_ID: |-
          {{ .tunnel_id }}
  data:
    - secretKey: tunnel_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 983e6186-8d86-427b-9120-79eb44aa06ac
        property: tunnel_id
    - secretKey: account_tag
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 983e6186-8d86-427b-9120-79eb44aa06ac
        property: account_tag
    - secretKey: tunnel_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 983e6186-8d86-427b-9120-79eb44aa06ac
        property: tunnel_secret
    - secretKey: tunnel_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 983e6186-8d86-427b-9120-79eb44aa06ac
        property: tunnel_id
