---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: adguard-home
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: adguard/adguardhome
      tag: v0.107.41
    service:
      main:
        enabled: true
        ports:
          http:
            port: 3000
            protocol: TCP
#      dns-tcp:
#        enabled: true
#        type: LoadBalancer
#        loadBalancerIP: '192.168.1.208'
#        externalTrafficPolicy: Local
#        ports:
#          dns-tcp:
#            enabled: true
#            port: &dns-port 53
#            protocol: TCP
#            targetPort: *dns-port
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: '192.168.1.208'
        externalTrafficPolicy: Local
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/enable: "true"
          hajimari.io/icon: shield-check
          hajimari.io/group: Network
          hajimari.io/appName: adguard
        hosts:
          - host: &host "adguard-home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        mountPath: /opt/adguardhome/conf
        size: 50Mi
        storageClass: ceph-block
        accessMode: ReadWriteOnce
